In [1]:
import pandas as pd

In [ ]:
## Series

# A Pandas series is one-dimentional array-like object that can hold any data type. It is similar to a column in  a table 

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print(series)
print(type(series))  # here In Series the 0 to 4 is index and the 1 to 5 is element. Basically the 0 index assign=1, 1 index assign=2, Similerley all 3 to 5 have indexing.

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [4]:
# Create a series from dictionery

data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [7]:
data=[10,20,30]
index=['a','b','c']

series=pd.Series(data,index)
print("Series \n",series)
print(type(series))

Series
 a    10
b    20
c    30
dtype: int64
<class 'pandas.Series'>

In [25]:
data={
    'Name':["Krish","Rohit","Amar"],
    'age':[32,25,30],
    'City':["Vadala","Kamothe","Kalyan"]

}

df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  age     City
0  Krish   32   Vadala
1  Rohit   25  Kamothe
2   Amar   30   Kalyan
<class 'pandas.DataFrame'>

In [16]:
## Create a Dataframe from a List of Dictionery

data=[
    {'Name':"Krish",'Age':32,'City':"Vadala"},
    {'Name':"John",'Age':34,'City':"Vadala"},
    {'Name':"Rohit",'Age':30,'City':"Vadala"},
    {'Name':"Amar",'Age':32,'City':"Vadala"}
]

df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age    City
0  Krish   32  Vadala
1   John   34  Vadala
2  Rohit   30  Vadala
3   Amar   32  Vadala
<class 'pandas.DataFrame'>

In [17]:
df

    Name  Age    City
0  Krish   32  Vadala
1   John   34  Vadala
2  Rohit   30  Vadala
3   Amar   32  Vadala

In [20]:
## Accessing A specified element

print(df.at[2,'Age'])

30

In [22]:
df.at[2,'Name']

'Rohit'

In [26]:
df

    Name  age     City
0  Krish   32   Vadala
1  Rohit   25  Kamothe
2   Amar   30   Kalyan

In [27]:
## Accessing a specified element using iat

df.iat[2,2]

'Kalyan'

In [28]:
## Data Manipulation with dataframe
df

    Name  age     City
0  Krish   32   Vadala
1  Rohit   25  Kamothe
2   Amar   30   Kalyan

In [ ]:
# Adding a column

df['Salary']=[50000,60000,70000]
df

    Name  age     City  Salary
0  Krish   32   Vadala   50000
1  Rohit   25  Kamothe   60000
2   Amar   30   Kalyan   70000

In [ ]:
# Removing a column

df.drop('Salary',axis=1)  # Here the Axis is not permentaly remove it has temporly

    Name  age     City
0  Krish   32   Vadala
1  Rohit   25  Kamothe
2   Amar   30   Kalyan

In [34]:
df

    Name  age     City  Salary
0  Krish   32   Vadala   50000
1  Rohit   25  Kamothe   60000
2   Amar   30   Kalyan   70000

In [35]:
# Removing the column permentaly

df.drop('Salary',axis=1,inplace=True)  # Here the we declare inplace=True for permentaly delete column.

In [36]:
df

    Name  age     City
0  Krish   32   Vadala
1  Rohit   25  Kamothe
2   Amar   30   Kalyan

In [38]:
## Add Age to the column

df['age']=df['age']+1
df

    Name  age     City
0  Krish   33   Vadala
1  Rohit   26  Kamothe
2   Amar   31   Kalyan

In [39]:

df.drop(0)

    Name  age     City
1  Rohit   26  Kamothe
2   Amar   31   Kalyan

In [40]:
df

    Name  age     City
0  Krish   33   Vadala
1  Rohit   26  Kamothe
2   Amar   31   Kalyan

In [41]:
df.drop(0,inplace=True)

In [42]:
df

    Name  age     City
1  Rohit   26  Kamothe
2   Amar   31   Kalyan